## Clase 1 - Introducción a Numpy

Numpy es una biblioteca para Python que facilita el manejo de arreglos multidimensionales y ofrece varias herramientas para trabajar con ellos. Muchas de las bibliotecas de Python que son ampliamente usadas hoy en día, como pandas, están construidas sobre numpy.

### Listas de Python vs arreglos de Numpy

A primera vista, un arreglo de numpy puede resultar idéntico a una lista de python, pero a medida que la cantidad de datos comienza a incrementar, los arreglos de numpy terminan ofreciendo un manejo más eficiente de la memoria.

Para comenzar, vamos a crear un arreglo de numpy:

In [1]:
import numpy as np

np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

Los arreglos pueden ser también multidimensionales:

In [2]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Es importante tener en cuenta que un arreglo de numpy tiene un tipo fijo de datos, entonces si se quiere agregar un dato de un tipo diferente al de la mayoría, este va a ser modificado para adaptarse al resto

In [3]:
enteros = np.array([1, 2, 3, 4])

Agrego un elemento de tipo flotante en la posición 1

In [4]:
enteros[1] = 8.4727
enteros

array([1, 8, 3, 4])

Numpy también nos permite crear arreglos con valores aleatorios del 0 al 1.
Basta con pasarle las dimensiones del arreglo que queremos crear.

In [5]:
np.random.rand(2, 3)

array([[0.04488421, 0.01982665, 0.34191856],
       [0.12875735, 0.90202681, 0.73519353]])

## Slicing

De la misma forma que con las listas de python, pueden obtenerse slices de los arreglos de numpy

In [6]:
enteros[:2]

array([1, 8])

In [7]:
matriz_de_enteros = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print('Original: ')
print(matriz_de_enteros)

print()

print('Recortada: ')
print(matriz_de_enteros[:2, :3])

Original: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Recortada: 
[[1 2 3]
 [5 6 7]]


In [8]:
# 3D
# arange() genera valores de un intervalo pasado por parámetro
# reshape() modifica la forma del numpy array

x = np.arange(45).reshape(3, 3, 5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [9]:
x[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
x[0][1]

array([5, 6, 7, 8, 9])

In [11]:
x[0][1][2]

7


¿Cómo conseguimos estos valores? ([fuente](https://towardsdatascience.com/indexing-and-slicing-of-1d-2d-and-3d-arrays-in-numpy-e731afff0bbe))

![title](img/matrix.png)

In [12]:
x[1:, 0:2, 1:4]

array([[[16, 17, 18],
        [21, 22, 23]],

       [[31, 32, 33],
        [36, 37, 38]]])

### Copia de arreglos

In [13]:
# Los arreglos no se copian con asignación

a = np.array([1, 2, 3, 4])
b = a
b

array([1, 2, 3, 4])

In [14]:
b[1] = 20
b

array([ 1, 20,  3,  4])

In [15]:
a

array([ 1, 20,  3,  4])

In [16]:
# Para copiar un arreglo a otra variable debemos usar copy()

a = np.array([1, 2, 3, 4])
b = a.copy()
b[1] = 20
b

array([ 1, 20,  3,  4])

In [17]:
a

array([1, 2, 3, 4])

### Modificación de dimensiones

Existen varias operaciones para cambiar la forma de un arreglo de numpy

In [18]:
matriz_de_enteros

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
# Obtener las dimensiones del arreglo

matriz_de_enteros.ndim

2

In [20]:
# Obtener la forma del arreglo

matriz_de_enteros.shape

(3, 4)

In [21]:
# Modificar la forma de un arreglo

enteros = np.array([3, 6, 9, 12])
print(f"enteros: {enteros}")
np.reshape(enteros, (2, 2))

enteros: [ 3  6  9 12]


array([[ 3,  6],
       [ 9, 12]])

In [22]:
# Aplanar un arreglo

a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

In [23]:
a.flatten()

array([1., 1., 1., 1.])

In [24]:
a

array([[1., 1.],
       [1., 1.]])

### Combinación de arreglos (Stacking)

In [25]:
# Los arreglos se pueden combinar verticalmente (se incrementa la cantidad de filas)

a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

In [26]:
b = np.arange(5, 10)
b

array([5, 6, 7, 8, 9])

In [27]:
combinados_verticalmente = np.vstack((a, b))
combinados_verticalmente

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
# También se pueden combinar horizontalmente (se incrementa la cantidad de columnas)

combinados_horizontalmente = np.hstack((a, b))
combinados_horizontalmente

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Operaciones matemáticas

In [29]:
a = np.array([1, 2, 3, 4])

a + 2

array([3, 4, 5, 6])

In [30]:
a ** 2

array([ 1,  4,  9, 16])

In [31]:
b = np.ones(4)
print(f"b: {b}")
a + b

b: [1. 1. 1. 1.]


array([2., 3., 4., 5.])

### Estadística

In [32]:
a = np.array([[5, 2, 1, 8], [26, 4, 17, 9]])

np.min(a)

1

In [33]:
np.max(a)

26

In [34]:
np.sum(a)

72

### Más magia

In [35]:
a = np.array([[5, 2, 1, 8], [26, 4, 17, 9]])

a > 5

array([[False, False, False,  True],
       [ True, False,  True,  True]])

In [36]:
a[a > 5]

array([ 8, 26, 17,  9])

### Broadcasting

Permite realizar operaciones entre dos numpy arrays de distintas dimensiones.
Para lograr esto, las dimensiones de los mismos deben ser compatibles. Dos dimensiones son compatibles cuando:
1. Son iguales
2. Alguna de las dos es 1

In [37]:
a = np.array([[5, 2, 1, 8], [26, 4, 17, 9]])
a

array([[ 5,  2,  1,  8],
       [26,  4, 17,  9]])

In [38]:
# Armamos un array que tenga la misma cantidad de columnas que a
b = np.array([5, 2, 1, 8])
print(f"a: {a.shape}")
print(f"b: {b.shape}")
# a + b
print()
print(f"a + b:\n {a + b}")

a: (2, 4)
b: (4,)

a + b:
 [[10  4  2 16]
 [31  6 18 17]]


In [39]:
# Armamos un array que tenga distinta cantidad de filas y columnas que a
b = np.array([5, 1, 8])
print(f"a: {a.shape}")
print(f"b: {b.shape}")
a + b

a: (2, 4)
b: (3,)


ValueError: operands could not be broadcast together with shapes (2,4) (3,) 

In [40]:
# Armamos un array que tenga la misma cantidad de filas que a
b = np.array([[2], [1]])
print(f"a: {a.shape}")
print(f"b: {b.shape}")
a + b

a: (2, 4)
b: (2, 1)


array([[ 7,  4,  3, 10],
       [27,  5, 18, 10]])

In [41]:
# Si b es un entero
b = 4
a + b

array([[ 9,  6,  5, 12],
       [30,  8, 21, 13]])