In [1]:

# # Clase 1 - Introducción a numpy

# Numpy es una biblioteca para Python que facilita el manejo de arreglos multidimensionales y ofrece varias herramientas para trabajar con ellos. Muchas de las bibliotecas de Python que son ampliamente usadas hoy en día, como pandas, están construidas sobre numpy.

# ## Listas de Python vs arreglos de Numpy

# A primera vista, un arreglo de numpy puede resultar idéntico a una lista de python, pero a medida que la cantidad de datos comienza a incrementar, los arreglos de numpy terminan ofreciendo un manejo más eficiente de la memoria.

# Para comenzar, vamos a crear un arreglo de numpy:

In [2]:


import numpy as np

np.array([1, 2, 3, 4])


# Los arreglos pueden ser también multidimensionales:

array([1, 2, 3, 4])

In [3]:


np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


# Es importante tener en cuenta que un arreglo de numpy tiene un tipo fijo de datos, entonces si se quiere agregar un dato de un tipo diferente al de la mayoría, este va a ser modificado para adaptarse al resto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:


enteros = np.array([1, 2, 3, 4])

# Agrego un elemento de tipo flotante en la posición 1

enteros[1] = 8.4727
enteros


# Numpy también nos permite crear arreglos con valores aleatorios del 0 al 1

array([1, 8, 3, 4])

In [5]:


# Basta con pasarle las dimensiones del arreglo que queremos crear

np.random.rand(2, 3)


# ## Slicing

# De la misma forma que con las listas de python, pueden obtenerse slices de los arreglos de numpy

array([[0.46381281, 0.34760138, 0.84878035],
       [0.08546414, 0.74445258, 0.53253671]])

In [6]:


enteros[:2]

array([1, 8])

In [7]:


matriz_de_enteros = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print('Original: ')
print(matriz_de_enteros)

print()

print('Recortada: ')
print(matriz_de_enteros[:2, :3])

Original: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Recortada: 
[[1 2 3]
 [5 6 7]]


### Copia de arreglos

In [8]:
# Los arreglos no se copian con asignación

a = np.array([1, 2, 3, 4])
b = a
b

array([1, 2, 3, 4])

In [9]:
b[1] = 20
b

array([ 1, 20,  3,  4])

In [10]:
a

array([ 1, 20,  3,  4])

In [11]:
# Para copiar un arreglo a otra variable debemos usar copy()

a = np.array([1, 2, 3, 4])
b = a.copy()
b[1] = 20
b

array([ 1, 20,  3,  4])

In [12]:
a

array([1, 2, 3, 4])

### Modificación de dimensiones

Existen varias operaciones para cambiar la forma de un arreglo de numpy

In [13]:
# Obtener las dimensiones del arreglo

matriz_de_enteros.ndim

2

In [14]:
# Obtener la forma del arreglo

matriz_de_enteros.shape

(3, 4)

In [15]:
# Modificar la forma de un arreglo

enteros = np.array([3, 6, 9, 12])
np.reshape(enteros, (2, 2))

array([[ 3,  6],
       [ 9, 12]])

In [16]:
# Aplanar un arreglo

a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

In [17]:
a.flatten()

array([1., 1., 1., 1.])

In [18]:
a

array([[1., 1.],
       [1., 1.]])

### Combinación de arreglos (Stacking)

In [19]:
# Los arreglos se pueden combinar verticalmente (se incrementa la cantidad de filas)

a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

In [20]:
b = np.arange(5, 10)
b

array([5, 6, 7, 8, 9])

In [21]:
combinados_verticalmente = np.vstack((a, b))
combinados_verticalmente

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
# También se pueden combinar horizontalmente (se incrementa la cantidad de columnas)

combinados_horizontalmente = np.hstack((a, b))
combinados_horizontalmente

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Operaciones matemáticas

In [23]:
a = np.array([1, 2, 3, 4])

a + 2

array([3, 4, 5, 6])

In [24]:
a ** 2

array([ 1,  4,  9, 16])

In [25]:
b = np.ones(4)
a + b

array([2., 3., 4., 5.])

### Estadística

In [26]:
a = np.array([[5, 2, 1, 8], [26, 4, 17, 9]])

np.min(a)

1

In [27]:
np.max(a)

26

In [28]:
np.sum(a)

72

### Más magia

In [29]:
a = np.array([[5, 2, 1, 8], [26, 4, 17, 9]])

a > 5

array([[False, False, False,  True],
       [ True, False,  True,  True]])

In [30]:
a[a > 5]

array([ 8, 26, 17,  9])